DELETE FROM CUATRIMESTRES;

INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('1er - 2010');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('2do - 2010');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('1er - 2011');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('2do - 2011');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('1er - 2012');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('2do - 2012');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('1er - 2013');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('2do - 2013');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('1er - 2014');
INSERT INTO CUATRIMESTRES (CUATRIMESTRE) VALUES ('2do - 2014');